### ISSUE TITLE
Use callback URL header for faas-flow request

### ISSUE THREAD

**Issue by chennqqi** [s8sg/faas-flow#109]
I found dag flow not return data in faas `callback`.  Shoud i use faas-flow's `callback`?
Why you made this design. can you share your thought

**Comment by s8sg** [comment]
The way currently OpenFaaS utilises callback is not gonna work with `faasflow` which has more than one node. The reason being openfaas calls the callback with the result of the first node. This is empty because `faas-flow` keep the intermediate result in `DataStore`. One option could be to get the callback url and call it from last node of workflow function. I'm not sure if the callback url get passed to the function. But even in that case for the first node the URL will be called with an empty data. I guess the best way is to have a `X-Faas-Flow-Callback-Url` which would eventually be called from faasflow rather than using `callback()` in workflow. What do you think of that ?

**Comment by chennqqi** [comment]
X-Faas-Flow-Callback-Url should be better way. The disadvantage of faas-flow sdk `callback` fixing callback url. That's not flexiable.

**Comment by s8sg** [comment]
I agree.

**Comment by s8sg** [comment]
@chennqqi This is merged
