### ISSUE TITLE
suggest add developing roadmap into README.md

### ISSUE THREAD

**Issue by chennqqi** [s8sg/faas-flow#94]
To share your plan and trend of this project

**Comment by s8sg** [comment]
Thats a really good suggestion. I guess the primary focus of project has shifted a bit in the recent time. The initial goal for this project was to provide a function composure for `OpenFaaS`. The new direction is to promote the usability of the core `sdk` so that the same pattern can be applied in other systems.

Although the main priority is to support function composition for `OpenFaaS` and related use cases like batch processing. 

### Faasflow issues:

#### Functional
##### Workflow Management
1. Issue #88 - Add ability to stop aand pause a flow
2. Issue #73 - Add ability to set retry count
3. Issue #74 - Timeout for operation 
4. Issue #75 - HTTP request as operation.  
##### Monitoring
1. Issue #89 - Handle Start and End event of operation
2. Issue #58 - Dynamic option tracing 
3. Tracing for queued noded
#### Non Functional
1. Issue #79 - Use persistence HTTP connection to improve speed
2. Use persistence DB connection for improving speed
#### Resource Management 
1. Maintain `faas-flow sdk` as  `lib-faas-flow` separately 
#### Other
1. Issue #37 - AWS State language interpreter for openfaas function


### faas-flow-tower issues:
#### Bug Fix
1. Fix traces for dynamic branches  (https://github.com/s8sg/faas-flow-tower/issues/9)
2. Fix sub-second tracing (may need changes in google chart) (https://github.com/s8sg/faas-flow-tower/issues/12)
3. Flow desc fix
#### Functional
1. Add Fetch log implementation 
2. Add delete flow implementation
3. All request for a flow in landing page
4. Grouping of operation by request Id
5. Add information of queued requests 
#### Resource Management 
1. Add deployment resource and script for default `StateStore` and `DataStore`
2. Add deployment resource and script for Jaguer 

Priority is :
1. Bug Fix
2. Functional Requirement 
3. Resource Management
4. Non Functional Requirement

@chennqqi Please let me know your thoughts

**Comment by chennqqi** [comment]
Here are two projects:
https://github.com/nuclio/nuclio
https://github.com/gaia-pipeline/gaia

I expect this project to:

1.  visualized like gaia. we can edit dag by drop and drag in graphic page.
2.  like nucli editable, we can edit script or flow function as modifier or forwarder in editor, and then auto deploy to faas.
3.  be a platform which compose simple functions to solve complicate proble. Compose any functions as piple/flow. like math, cut difficult problem into easy pieces. k8s/swarm aim to schedual
docker/cpu/memory while we need an project to schedual simple functions

Hope you can understand my chinese english...

**Comment by s8sg** [comment]
@chennqqi 
Those are very long term Roadmap. Currently we don't have any long term roadmap, neither I can think of any. We will keep evolving `faas-flow` based on the current requirements that we have.  Both of the project that you mentioned is quite matured. Also as I initially said `faas-flow` will be currently only based on openfaas as a runtime. 

The right way would be to create a proposal for the features in details and have references from other projects if needed. The feature not need to be abstract and need to be in point on what is expected, whats are the values, what are the sub features.
 
For example
1. Heading: UI based DAG editor
2. Description: Allow user to edit DAG on the UI 
3. Sub Features: <all features expected>
4. reference: <references of those features in other system>
5. Values:  <the values of those features>

Once we have it as an Issue we will put into a RoadMap. We also need to consider the deficit of contributors, specially for frontend.  While we have it well documented in issue, we can ask for help.
